# Generated by Django 4.2.10 on 2024-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0004_subscription_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="последнее обновление"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="стоимость"
            ),
        ),
    ]
